arena:
  temizleyici-saniye: 8
  enabled-maps:
    - "allah1337"

chat:
  blacklisted-words:
    - orospu
    - sik
    - yarrak
    - yarak
    - yarram
    - sikik
    - anani
    - avradini
    - bacini
    - pic
    - orosbu
    - sikim
    - siktir
    - siktigim
    - sikerim
    - siktir
    - siktirlan
    - yavsak
    - gay
    - lezbiyen
    - travesti
    - sikis
    - anan
    - gavat
    - gavad
    - yarragim
    - orosbunun
    - orospunun
    - am
    - amini
    - yarramin
    - got
    - gotune
    - amina
    - sikkafa
    - sikini
    - yarragini
    - aminiyolunu
    - gotunubasini
    - yarramin
    - cikerim
    - fakarim
    - fuck
    - bitch
    - sike
    - sikimin
    - orosbunun
    - orospunun
    - siktirla
    - desiktir
    - seks
    - sex
    - porno
    - penis
    - vajina
    - cock
    - vagina
    - durzu
    - pezevenk
    - dumbullu
    - putperest
    - akp
    - mhp
    - chp
    - bbp
    - bdp
    - tayyip
    - oc
    - sikikin
    - sikcigim
    - sikecegim
    - siksiz
    - cuksuz
    - amli
    - amsiz